export const actions = {
  GET_PRODUCTS: "GET_PRODUCTS",
  GET_PRODUCTS_FAILED: "GET_PRODUCTS_FAILED",
  GET_CHAT: "GET_CHAT",
  GET_CHAT_FAILED: "GET_CHAT_FAILED",
};

export const auth = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",

  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAILURE: "SIGNUP_FAILURE",
};

export const cart = {
  ADD_TO_CART_REQUEST: "ADD_TO_CART_REQUEST",
  ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
  ADD_TO_CART_FAILURE: "ADD_TO_CART_FAILURE",
  RESET_CART: "RESET_CART",
  REMOVE_CART_ITEM_REQUEST: "REMOVE_CART_ITEM_REQUEST",
  REMOVE_CART_ITEM_SUCCESS: "REMOVE_CART_ITEM_SUCCESS",
  REMOVE_CART_ITEM_FAILURE: "REMOVE_CART_ITEM_FAILURE",
};

export const order = {
  ADD_TO_ORDER_REQUEST: "ADD_TO_ORDER_REQUEST",
  ADD_TO_ORDER_SUCCESS: "ADD_TO_ORDER_SUCCESS",
  ADD_TO_ORDER_FAILURE: "ADD_TO_ORDER_FAILURE",
  RESET_ORDER: "RESET_ORDER",
  REMOVE_ORDER_ITEM_REQUEST: "REMOVE_ORDER_ITEM_REQUEST",
  REMOVE_ORDER_ITEM_SUCCESS: "REMOVE_ORDER_ITEM_SUCCESS",
  REMOVE_ORDER_ITEM_FAILURE: "REMOVE_ORDER_ITEM_FAILURE",
};
